baseURL = "https://martnquesada.github.io/"
languageCode = "en-us"
title = "Martín Quesada Zaragoza"
theme = "notrack"
newContentEditor = "nvim"
mainSections = ["blog"]
disqusShortname = "https-martnquesada-github-io"
[pagination]
  pagerSize = 4

ignoreErrors = ["error-missing-instagram-accesstoken"]

[params]
  author = "Martín Quesada Zaragoza"
  siteHeading = "Martín Quesada" # defaults to author
  showBlogLatest = true
  mainSections = ["blog"]
  showTaxonomyLinks = false
  nBlogLatest = 4 # number of blog post om the home page
  blogLatestHeading = "Blog"

  [params.social]
    email = "mquesadazaragoza@gmail.com"
    github = "martnquesada"
    linkedin = "martín-quesada-zaragoza-a20919184"

[taxonomies]
  year = "year"
  month = "month"
  tags = "tags"
  categories = "categories"

[permalinks]
  blog = "/blog/:year/:month/:slug"
